### ISSUE TITLE
Server Status 401 Error Fix / Set notificationPriority by default as critical

### ISSUE THREAD

**Issue by eckonator** [klein0r/fhem-lametric#10]
Hi, i use your lametic fhem module - thanks for this.
I find out, that if the lametic time is in screensaver mode, no notifications send by the fhem modul will be shown. After some debugging, i saw that the lamatic times response is a 401 error code.

The error code says:

> Only notifications with priority 'critical' are allowed when screensaver is activated

So i have fixed this problem with the following attribute for my lametric device:

`attr LaMetric notificationPriority critical`

But i think it's better to set the notificationPriority for default as critical:

70_LaMetric.pm, Line 526, change the following:

`$values{priority} = AttrVal($hash->{NAME}, "notificationPriority", "info");`

to the new value:

`$values{priority} = AttrVal($hash->{NAME}, "notificationPriority", "critical");`

Hope it find a way into the master branch :)

**Comment by klein0r** [comment]
You configured it the right way. This is intended behaviour. You can use the attribute notificationPriority to override my default (as you did). No need for a change in my opinion
